In [3]:
import requests
from bs4 import BeautifulSoup
import mysql
import mysql.connector
import pandas as pd

In [84]:
wc2018 = pd.read_csv(r"C:\Users\varad\OneDrive - Umich\Documents\Euro2021\wc2018.csv")
wc2022 = pd.read_csv(r"C:\Users\varad\OneDrive - Umich\Documents\Euro2021\wc2022.csv")
nl2022 = pd.read_csv(r"C:\Users\varad\OneDrive - Umich\Documents\Euro2021\nl2022.csv")
euro2016 = pd.read_csv(r"C:\Users\varad\OneDrive - Umich\Documents\Euro2021\Euro2016.csv")
euro2021 = pd.read_csv(r"C:\Users\varad\OneDrive - Umich\Documents\Euro2021\rEuro2021.csv")

In [85]:
dfs = [wc2018, wc2022, nl2022, euro2016, euro2021]
comp = ['wc2018', 'wc2022', 'nl2022', 'euro2016', 'euro2021']
## Add back competitition column

In [86]:

df = pd.concat(dfs).fillna(0).drop('id', axis = 1)
# df = df.fillna(0)
# df = df.drop('id', axis = 1)
df

,squad,played90s,avgpossession,goalsx90,assistsx90,expgoalsx90,diffgoalx90
0,Belgium,7.0,52.9,2.14,1.71,1.90,0.24
1,Croatia,8.0,56.7,1.62,1.00,1.40,0.22
2,Denmark,4.3,43.0,0.69,0.69,0.68,0.01
3,England,7.7,54.1,1.57,0.78,1.46,0.11
4,France,7.0,48.3,1.71,0.86,1.30,0.41
...,...,...,...,...,...,...,...
12,Scotland,3.0,43.7,0.33,0.00,1.30,-0.97
13,Slovakia,3.0,45.0,0.33,0.33,0.34,-0.01
14,Spain,7.0,72.0,1.43,1.29,2.38,-0.95
15,Switzerland,5.7,48.0,1.41,1.41,1.26,0.15
16,Türkiye,3.0,49.0,0.33,0.33,1.01,-0.68